name: "owserverusb"
description: "Home Assistant add-on for owserver using USB hub for 1-wire"
version: "0.0.1"
slug: owserverusb
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
url: https://github.com/myllo/owserverusb
ports:
  4403/tcp: 4403
