version: '3'
services:
  owfs:
    build: .
    devices:
      - /dev/bus/usb/
#      - /dev/fuse
    ports:
      - 2122:2121
      - 4304:4304
    volumes:
      - ./owfs.conf:/etc/owfs.conf:ro
#    cap_add:
#      - SYS_ADMIN
